### ISSUE TITLE
左侧点击全选checkbox后不能移动到右侧

### ISSUE THREAD

**Issue by teiyaki** [dyxweb/TreeTransfer#3]
很棒的组件，感谢作者的分享！
但是我发现有一个小问题，点击左侧树下方的全选checkbox后点击向右按钮，并不能如期将左侧的项目移动到右侧，而手动逐个勾选左侧树的项目是可以移动到右侧的。简单浏览了一下代码，发现此处代码似乎有些问题，this.state.datasource是否应改为this.state.leftTree.dataSource？
https://github.com/dyxweb/TreeTransfer/blob/b4526a06ed1468a964d4f18788a27db161f16b0d/src/components/treeTransfer/index.js#L396

**Comment by dyxweb** [comment]
感谢您的反馈！
从本地的demo来看貌似并没有复现您说的问题，您提供的那行代码，应该是没有问题的，由于全选左侧的tree，代表这选择了全部数据，所以用的是this.state.dataSource的全量数据。 麻烦给提供一下复现场景。

**Comment by dyxweb** [comment]
目前没有发现上述问题
